### PR TITLE
DMs Off Error Handling

### LINKED ISSUE #23: DMs Off Error Handling
In the .linkgh command, the `Forbidden` error gets raised if the user's DMs are closed. The solution is an error handler telling the user to open their DMs.

### PR DESCRIPTION
**Pull request by Dorukyum**

### CODE REVIEW

**Comment by Dorukyum** [comment]
Update: I used `black` to format both files. `stackexchange.py` didn't have any changes but `github.py` was formatted.

**Comment by Dorukyum** [comment]
I forgot to paste stackexchange.py's formatted code the last time. I got it this time.

**Comment by FalseDev** [comment]
It looks like `stackexchange.py` and `github.py` are interchanged somehow :sweat_smile:

**Comment by Dorukyum** [comment]
I don't know how I missed that. It's done now.

**Comment by FalseDev** [comment]
Just a tiny issue, the `except discord.Forbidden` parts should be changed to just `Forbidden` and `Forbidden` has to be imported from `discord`

Make sure to run black on the changed files as well

**Review by FalseDev — APPROVED** [review]
Everything looks good!

**Pull request merged**
